backend:
  name: git-gateway
  branch: master

logo_url: https://rev-labs.netlify.app/media/logo-no-background.svg

media_folder: "media"
public_folder: "media"
publish_mode: editorial_workflow

collections:
  - label: "Index"
    name: "index"
    files:
      - label: "Text"
        name: "info"
        format: "json"
        file: "content/index.json"
        fields:
          - {label: "Message", name: "message", widget: "string"}