backend:
  name: git-gateway
  branch: master

logo_url: https://rev-labs.netlify.app/media/logo-no-background.svg

media_folder: "media"
public_folder: "media"
publish_mode: editorial_workflow
collections:
  - label: "About"
    name: "about"
    files:
    - label: "About"
      name: "info"
      format: 'json'
      file: "content/about.json"
      fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
