backend:
  name: git-gateway
  branch: master

logo_url: https://rev-labs.netlify.app/media/logo-no-background.svg

media_folder: "media"
public_folder: "media"
publish_mode: editorial_workflow

collections:
  - label: "Index"
    name: "index"
    files:
      - label: "Text"
        name: "info"
        format: "json"
        file: "content/index.json"
        fields:
          - {label: "Message", name: "message", widget: "string"}

  - label: "Posts"
    name: "posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
