backend:
  name: git-gateway
  branch: master

logo_url: https://rev-labs.netlify.app/media/logo-no-background.svg

media_folder: "media"
public_folder: "media"
publish_mode: editorial_workflow
collections:
  - label: "Landing page"
    name: "Landing page"
    files:
    - label: "Page text"
      name: "info"
      format: 'json'
      file: "content/about.json"
      fields:
        - {label: "Message", name: message, widget: string}
